[package]
name = "romp"
version = "0.0.1"
authors = ["Andrew Whatson <whatson@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
lazy_static = "1.3"
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15"

[lib]
proc-macro = true
